# Generated by Django 4.0.2 on 2022-02-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_middle_name_user_name_user_surname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
