# Generated by Django 4.0.2 on 2022-02-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Gadgets', 'Gadgets'), ('Robotics', 'Robotics'), ('IoT', 'IoT')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
